import "@/styles/globals.css";
import { useState } from "react";
import Sidebar from "./components/Sidebar";
import Headers from "./components/Header";
import Head from "next/head";
export default function App({ Component, pageProps }) {
  const[showSidebar,setShowSidebar]=useState(false)
  return (
    <><Head>
      <title>Faketify</title>
      <meta name="description" content="Generated by create next app"></meta>
   <link rel="icon" href="/favicon.ico"/>
    </Head>
      <div className="bg-spotify-lightgray min-h-screen text-gray-300">
        <Headers setShowSidebar={setShowSidebar}/>
        <Sidebar showSidebar={showSidebar} setShowSidebar={setShowSidebar}/>
        <main>
          <Component {...pageProps} />
        </main>
      </div>
    </>
  );
}
